In [1]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt


In [2]:
%matplotlib inline

In [3]:
DIRECTORY = r'train'

CATEGORIES = ['dense', 'normal']

In [4]:
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])


In [5]:
data


[[array([[ 61,  67,  89, ...,  98,  96,  89],
         [ 63,  73,  63, ..., 101,  96,  93],
         [ 70,  74,  73, ...,  93,  91,  90],
         ...,
         [ 60,  55,  63, ...,  61,  68,  72],
         [ 57,  66,  65, ...,  74,  64,  69],
         [ 57,  79,  66, ...,  56,  84,  61]], dtype=uint8),
  0],
 [array([[89, 85, 76, ..., 65, 60, 66],
         [92, 91, 63, ..., 61, 56, 54],
         [93, 82, 72, ..., 61, 64, 54],
         ...,
         [69, 81, 79, ..., 75, 81, 79],
         [71, 77, 77, ..., 66, 49, 76],
         [77, 83, 78, ..., 57, 66, 80]], dtype=uint8),
  0],
 [array([[66, 60, 51, ..., 83, 73, 77],
         [77, 59, 75, ..., 64, 87, 99],
         [76, 55, 67, ..., 67, 83, 89],
         ...,
         [69, 76, 50, ..., 59, 60, 53],
         [58, 65, 72, ..., 70, 52, 53],
         [69, 61, 75, ..., 70, 73, 84]], dtype=uint8),
  0],
 [array([[72, 80, 81, ..., 84, 56, 70],
         [75, 94, 83, ..., 66, 87, 60],
         [81, 89, 88, ..., 85, 74, 77],
         ...,
     

In [6]:

data[0][1]

0

In [7]:
import random

random.shuffle(data)


In [8]:
X = []
y = []


In [9]:
for features, label in data:
    X.append(features)
    y.append(label)


In [10]:
X = np.array(X)
y = np.array(y)


In [11]:
X

array([[[ 85,  96,  89, ...,  72,  68,  67],
        [ 84,  92,  68, ...,  72,  69,  64],
        [100,  78,  80, ...,  58,  51,  61],
        ...,
        [ 88,  71,  37, ...,  72,  91,  94],
        [ 61,  51,  51, ...,  79,  87,  88],
        [ 68,  89,  60, ...,  88,  98,  90]],

       [[ 64,  65,  80, ...,  81,  93,  86],
        [ 84,  88,  79, ...,  87,  91,  76],
        [ 77,  73,  75, ...,  81,  84,  97],
        ...,
        [ 68,  86,  65, ...,  49,  52,  50],
        [ 71,  69,  65, ...,  80,  74,  49],
        [ 70,  69,  58, ...,  54,  59,  71]],

       [[ 97,  98,  92, ..., 105, 112, 113],
        [ 87,  78,  86, ..., 110, 104, 111],
        [ 88,  91, 133, ..., 109, 108, 109],
        ...,
        [112, 114, 104, ..., 112, 104, 112],
        [109, 109, 113, ..., 109, 110, 108],
        [109, 106, 110, ..., 101, 112, 106]],

       ...,

       [[ 99,  90, 132, ...,  40,  61,  29],
        [ 76, 131, 130, ...,  47,  36,  70],
        [112, 143, 133, ...,  53,  90,  73

In [12]:
y

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [13]:

import pickle

In [14]:

pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))



In [15]:
X

array([[[ 85,  96,  89, ...,  72,  68,  67],
        [ 84,  92,  68, ...,  72,  69,  64],
        [100,  78,  80, ...,  58,  51,  61],
        ...,
        [ 88,  71,  37, ...,  72,  91,  94],
        [ 61,  51,  51, ...,  79,  87,  88],
        [ 68,  89,  60, ...,  88,  98,  90]],

       [[ 64,  65,  80, ...,  81,  93,  86],
        [ 84,  88,  79, ...,  87,  91,  76],
        [ 77,  73,  75, ...,  81,  84,  97],
        ...,
        [ 68,  86,  65, ...,  49,  52,  50],
        [ 71,  69,  65, ...,  80,  74,  49],
        [ 70,  69,  58, ...,  54,  59,  71]],

       [[ 97,  98,  92, ..., 105, 112, 113],
        [ 87,  78,  86, ..., 110, 104, 111],
        [ 88,  91, 133, ..., 109, 108, 109],
        ...,
        [112, 114, 104, ..., 112, 104, 112],
        [109, 109, 113, ..., 109, 110, 108],
        [109, 106, 110, ..., 101, 112, 106]],

       ...,

       [[ 99,  90, 132, ...,  40,  61,  29],
        [ 76, 131, 130, ...,  47,  36,  70],
        [112, 143, 133, ...,  53,  90,  73

In [16]:
y

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [17]:
X = X/255

In [18]:
X

array([[[0.33333333, 0.37647059, 0.34901961, ..., 0.28235294,
         0.26666667, 0.2627451 ],
        [0.32941176, 0.36078431, 0.26666667, ..., 0.28235294,
         0.27058824, 0.25098039],
        [0.39215686, 0.30588235, 0.31372549, ..., 0.22745098,
         0.2       , 0.23921569],
        ...,
        [0.34509804, 0.27843137, 0.14509804, ..., 0.28235294,
         0.35686275, 0.36862745],
        [0.23921569, 0.2       , 0.2       , ..., 0.30980392,
         0.34117647, 0.34509804],
        [0.26666667, 0.34901961, 0.23529412, ..., 0.34509804,
         0.38431373, 0.35294118]],

       [[0.25098039, 0.25490196, 0.31372549, ..., 0.31764706,
         0.36470588, 0.3372549 ],
        [0.32941176, 0.34509804, 0.30980392, ..., 0.34117647,
         0.35686275, 0.29803922],
        [0.30196078, 0.28627451, 0.29411765, ..., 0.31764706,
         0.32941176, 0.38039216],
        ...,
        [0.26666667, 0.3372549 , 0.25490196, ..., 0.19215686,
         0.20392157, 0.19607843],
        [0.2

In [19]:
X = X.reshape(-1, 60, 60, 1)

In [20]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten



In [21]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))


In [22]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


     

In [23]:
model.fit(X, y, epochs=100, validation_split=0.1)


Epoch 1/100
9/9 [==============================] - 4s 273ms/step - loss: 0.7015 - accuracy: 0.4928 - val_loss: 0.6931 - val_accuracy: 0.4839
Epoch 2/100
9/9 [==============================] - 2s 222ms/step - loss: 0.6919 - accuracy: 0.4964 - val_loss: 0.6936 - val_accuracy: 0.4839
Epoch 3/100
9/9 [==============================] - 2s 209ms/step - loss: 0.6886 - accuracy: 0.4892 - val_loss: 0.6915 - val_accuracy: 0.4839
Epoch 4/100
9/9 [==============================] - 2s 208ms/step - loss: 0.6768 - accuracy: 0.5216 - val_loss: 0.6983 - val_accuracy: 0.5161
Epoch 5/100
9/9 [==============================] - 2s 195ms/step - loss: 0.6966 - accuracy: 0.5396 - val_loss: 0.6874 - val_accuracy: 0.6129
Epoch 6/100
9/9 [==============================] - 2s 209ms/step - loss: 0.6596 - accuracy: 0.6547 - val_loss: 0.6757 - val_accuracy: 0.6129
Epoch 7/100
9/9 [==============================] - 2s 194ms/step - loss: 0.6208 - accuracy: 0.6295 - val_loss: 0.6763 - val_accuracy: 0.5806
Epoch 8/100
9

In [24]:
X.shape

(309, 60, 60, 1)

In [25]:
import time

time.time()


1670705922.0821056

In [26]:
type(1581428129.5990093)

float

In [28]:
import pickle

X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

X = X/255

X = X.reshape(-1, 60, 60, 1)

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

from keras.callbacks import TensorBoard
import time

dense_layers = [3]
conv_layers = [3]
neurons = [64]


for dense_layer in dense_layers:
	for conv_layer in conv_layers:
		for neuron in neurons:

			NAME = '{}-denselayer-{}-convlayer-{}-neuron-{}'.format(dense_layer, conv_layer, neuron, int(time.time()))
			tensorboard = TensorBoard(log_dir = 'logs2\\{}'.format(NAME))


			model = Sequential()

			for l in range(conv_layer):
				model.add(Conv2D(neuron, (3,3), activation = 'relu'))
				model.add(MaxPooling2D((2,2)))

			model.add(Flatten())

			model.add(Dense(neuron, input_shape = X.shape[1:], activation = 'relu'))

			for l in range(dense_layer - 1):
				model.add(Dense(neuron, activation = 'relu'))

			model.add(Dense(2, activation = 'softmax'))

			model.compile(optimizer='adam',
			              loss='sparse_categorical_crossentropy',
			              metrics=['accuracy'])

			print('===================================================================================================================================')
			print('===================================================================================================================================')
			print('=========================================== RUNNING MODEL =========================================================================')
			print('=================================================='+ NAME + '======================================================================')
			print('===================================================================================================================================')
			print('===================================================================================================================================')

			model.fit(X, y, epochs=200, batch_size = 32, validation_split=0.1, callbacks = [tensorboard])

			model.save('image_processing.model')

=========================================== RUNNING MODEL =========================================================================
==================================================3-denselayer-3-convlayer-64-neuron-1670706011======================================================================
Epoch 1/200
9/9 [==============================] - 4s 239ms/step - loss: 0.6937 - accuracy: 0.4784 - val_loss: 0.6936 - val_accuracy: 0.4839
Epoch 2/200
9/9 [==============================] - 2s 196ms/step - loss: 0.6929 - accuracy: 0.5576 - val_loss: 0.6927 - val_accuracy: 0.4839
Epoch 3/200
9/9 [==============================] - 2s 202ms/step - loss: 0.6905 - accuracy: 0.4892 - val_loss: 0.6941 - val_accuracy: 0.4839
Epoch 4/200
9/9 [==============================] - 2s 203ms/step - loss: 0.6883 - accuracy: 0.4892 - val_loss: 0.6899 - val_accuracy: 0.5806
Epoch 5/200
9/9 [==============================] - 2s 189ms/step - loss: 0.6934 - accuracy: 0.5180 - val_loss: 0.6908 - val_accuracy: 0.51

INFO:tensorflow:Assets written to: image_processing.model\assets


INFO:tensorflow:Assets written to: image_processing.model\assets


In [29]:
import cv2
import keras


In [30]:
import numpy as np
CATEGORIES = ['dense', 'normal']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr

model = keras.models.load_model('image_processing.model')


In [35]:
prediction = model.predict([image('train/dense/226788_sat_78.jpg')])
print(CATEGORIES[prediction.argmax()])


1/1 [==============================] - 0s 31ms/step
normal
