In [1]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt


In [2]:
%matplotlib inline

In [3]:
DIRECTORY = r'sample_data'

CATEGORIES = ['dense', 'normal']

In [4]:
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])


In [5]:
data


[[array([[ 61,  67,  89, ...,  98,  96,  89],
         [ 63,  73,  63, ..., 101,  96,  93],
         [ 70,  74,  73, ...,  93,  91,  90],
         ...,
         [ 60,  55,  63, ...,  61,  68,  72],
         [ 57,  66,  65, ...,  74,  64,  69],
         [ 57,  79,  66, ...,  56,  84,  61]], dtype=uint8),
  0],
 [array([[89, 85, 76, ..., 65, 60, 66],
         [92, 91, 63, ..., 61, 56, 54],
         [93, 82, 72, ..., 61, 64, 54],
         ...,
         [69, 81, 79, ..., 75, 81, 79],
         [71, 77, 77, ..., 66, 49, 76],
         [77, 83, 78, ..., 57, 66, 80]], dtype=uint8),
  0],
 [array([[66, 60, 51, ..., 83, 73, 77],
         [77, 59, 75, ..., 64, 87, 99],
         [76, 55, 67, ..., 67, 83, 89],
         ...,
         [69, 76, 50, ..., 59, 60, 53],
         [58, 65, 72, ..., 70, 52, 53],
         [69, 61, 75, ..., 70, 73, 84]], dtype=uint8),
  0],
 [array([[72, 80, 81, ..., 84, 56, 70],
         [75, 94, 83, ..., 66, 87, 60],
         [81, 89, 88, ..., 85, 74, 77],
         ...,
     

In [6]:

data[0][1]

0

In [7]:
import random

random.shuffle(data)


In [8]:
X = []
y = []


In [9]:
for features, label in data:
    X.append(features)
    y.append(label)


In [10]:
X = np.array(X)
y = np.array(y)


In [11]:
X

array([[[ 62,  60,  57, ...,  82,  81,  85],
        [ 73,  73,  81, ...,  86,  91,  59],
        [ 84,  42,  74, ...,  92, 105,  88],
        ...,
        [ 70,  76,  58, ...,  83,  89, 141],
        [ 78,  55,  77, ...,  83,  86, 123],
        [ 54,  68,  87, ...,  97,  70,  71]],

       [[ 97,  96,  97, ...,  95,  86,  73],
        [ 81,  71,  95, ...,  89, 101, 104],
        [107,  83,  85, ...,  74, 105,  92],
        ...,
        [ 86,  81,  82, ...,  93, 110, 105],
        [100,  68, 104, ..., 108, 108, 111],
        [104,  77, 105, ..., 100,  95,  83]],

       [[ 58,  64,  83, ...,  59,  99,  67],
        [ 72,  71,  81, ...,  57,  94,  70],
        [ 76,  77,  98, ...,  82, 109,  82],
        ...,
        [ 75,  71,  75, ...,  52,  69,  59],
        [ 63,  50,  99, ...,  67,  85,  78],
        [ 76,  62,  84, ...,  89,  63,  89]],

       ...,

       [[ 93,  95,  89, ..., 106, 109, 110],
        [ 96,  95,  92, ..., 110, 109, 110],
        [ 87,  88,  82, ..., 111, 113, 109

In [12]:
y

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,

In [13]:

import pickle

In [14]:

pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))



In [15]:
X

array([[[ 62,  60,  57, ...,  82,  81,  85],
        [ 73,  73,  81, ...,  86,  91,  59],
        [ 84,  42,  74, ...,  92, 105,  88],
        ...,
        [ 70,  76,  58, ...,  83,  89, 141],
        [ 78,  55,  77, ...,  83,  86, 123],
        [ 54,  68,  87, ...,  97,  70,  71]],

       [[ 97,  96,  97, ...,  95,  86,  73],
        [ 81,  71,  95, ...,  89, 101, 104],
        [107,  83,  85, ...,  74, 105,  92],
        ...,
        [ 86,  81,  82, ...,  93, 110, 105],
        [100,  68, 104, ..., 108, 108, 111],
        [104,  77, 105, ..., 100,  95,  83]],

       [[ 58,  64,  83, ...,  59,  99,  67],
        [ 72,  71,  81, ...,  57,  94,  70],
        [ 76,  77,  98, ...,  82, 109,  82],
        ...,
        [ 75,  71,  75, ...,  52,  69,  59],
        [ 63,  50,  99, ...,  67,  85,  78],
        [ 76,  62,  84, ...,  89,  63,  89]],

       ...,

       [[ 93,  95,  89, ..., 106, 109, 110],
        [ 96,  95,  92, ..., 110, 109, 110],
        [ 87,  88,  82, ..., 111, 113, 109

In [16]:
y

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,

In [17]:
X = X/255

In [18]:
X

array([[[0.24313725, 0.23529412, 0.22352941, ..., 0.32156863,
         0.31764706, 0.33333333],
        [0.28627451, 0.28627451, 0.31764706, ..., 0.3372549 ,
         0.35686275, 0.23137255],
        [0.32941176, 0.16470588, 0.29019608, ..., 0.36078431,
         0.41176471, 0.34509804],
        ...,
        [0.2745098 , 0.29803922, 0.22745098, ..., 0.3254902 ,
         0.34901961, 0.55294118],
        [0.30588235, 0.21568627, 0.30196078, ..., 0.3254902 ,
         0.3372549 , 0.48235294],
        [0.21176471, 0.26666667, 0.34117647, ..., 0.38039216,
         0.2745098 , 0.27843137]],

       [[0.38039216, 0.37647059, 0.38039216, ..., 0.37254902,
         0.3372549 , 0.28627451],
        [0.31764706, 0.27843137, 0.37254902, ..., 0.34901961,
         0.39607843, 0.40784314],
        [0.41960784, 0.3254902 , 0.33333333, ..., 0.29019608,
         0.41176471, 0.36078431],
        ...,
        [0.3372549 , 0.31764706, 0.32156863, ..., 0.36470588,
         0.43137255, 0.41176471],
        [0.3

In [19]:
X = X.reshape(-1, 60, 60, 1)

In [20]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten



In [21]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))


In [22]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


     

In [23]:
model.fit(X, y, epochs=100, validation_split=0.1)


Epoch 1/100
9/9 [==============================] - 4s 274ms/step - loss: 0.7076 - accuracy: 0.5000 - val_loss: 0.6910 - val_accuracy: 0.5806
Epoch 2/100
9/9 [==============================] - 2s 220ms/step - loss: 0.6942 - accuracy: 0.4640 - val_loss: 0.6936 - val_accuracy: 0.4194
Epoch 3/100
9/9 [==============================] - 2s 217ms/step - loss: 0.6927 - accuracy: 0.4712 - val_loss: 0.6922 - val_accuracy: 0.5806
Epoch 4/100
9/9 [==============================] - 2s 217ms/step - loss: 0.6917 - accuracy: 0.5216 - val_loss: 0.7009 - val_accuracy: 0.4194
Epoch 5/100
9/9 [==============================] - 2s 216ms/step - loss: 0.6966 - accuracy: 0.5216 - val_loss: 0.7008 - val_accuracy: 0.4194
Epoch 6/100
9/9 [==============================] - 2s 217ms/step - loss: 0.6904 - accuracy: 0.5360 - val_loss: 0.6912 - val_accuracy: 0.5484
Epoch 7/100
9/9 [==============================] - 2s 212ms/step - loss: 0.6857 - accuracy: 0.6511 - val_loss: 0.6730 - val_accuracy: 0.5806
Epoch 8/100
9

In [24]:
X.shape

(309, 60, 60, 1)

In [25]:
import time

time.time()


1670755777.8888822

In [26]:
type(1581428129.5990093)

float

In [30]:
import pickle

X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

X = X/255

X = X.reshape(-1, 60, 60, 1)

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

from keras.callbacks import TensorBoard
import time

dense_layers = [3]
conv_layers = [3]
neurons = [64]


for dense_layer in dense_layers:
	for conv_layer in conv_layers:
		for neuron in neurons:

			NAME = '{}-denselayer-{}-convlayer-{}-neuron-{}'.format(dense_layer, conv_layer, neuron, int(time.time()))
			tensorboard = TensorBoard(log_dir = 'logs2\\{}'.format(NAME))


			model = Sequential()

			for l in range(conv_layer):
				model.add(Conv2D(neuron, (3,3), activation = 'relu'))
				model.add(MaxPooling2D((2,2)))

			model.add(Flatten())

			model.add(Dense(neuron, input_shape = X.shape[1:], activation = 'relu'))

			for l in range(dense_layer - 1):
				model.add(Dense(neuron, activation = 'relu'))

			model.add(Dense(2, activation = 'softmax'))

			model.compile(optimizer='adam',
			              loss='sparse_categorical_crossentropy',
			              metrics=['accuracy'])

			print('===================================================================================================================================')
			print('===================================================================================================================================')
			print('=========================================== RUNNING MODEL =========================================================================')
			print('=================================================='+ NAME + '======================================================================')
			print('===================================================================================================================================')
			print('===================================================================================================================================')

			model.fit(X, y, epochs=10, batch_size = 32, validation_split=0.1, callbacks = [tensorboard])

			model.save('image_processing.h5')

=========================================== RUNNING MODEL =========================================================================
==================================================3-denselayer-3-convlayer-64-neuron-1670756382======================================================================
Epoch 1/10
9/9 [==============================] - 4s 243ms/step - loss: 0.6942 - accuracy: 0.5288 - val_loss: 0.6927 - val_accuracy: 0.5484
Epoch 2/10
9/9 [==============================] - 2s 202ms/step - loss: 0.6931 - accuracy: 0.5324 - val_loss: 0.6934 - val_accuracy: 0.5161
Epoch 3/10
9/9 [==============================] - 2s 214ms/step - loss: 0.6921 - accuracy: 0.4892 - val_loss: 0.6825 - val_accuracy: 0.5806
Epoch 4/10
9/9 [==============================] - 2s 198ms/step - loss: 0.6943 - accuracy: 0.4856 - val_loss: 0.6978 - val_accuracy: 0.4194
Epoch 5/10
9/9 [==============================] - 2s 198ms/step - loss: 0.6903 - accuracy: 0.5288 - val_loss: 0.6846 - val_accuracy: 0.5806
Ep

In [29]:
import cv2
import keras


In [30]:
import numpy as np
CATEGORIES = ['dense', 'normal']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr

model = keras.models.load_model('image_processing.model')


In [35]:
prediction = model.predict([image('train/dense/226788_sat_78.jpg')])
print(CATEGORIES[prediction.argmax()])


1/1 [==============================] - 0s 31ms/step
normal
